### ISSUE TITLE
Bundle configuration documentation missing

### ISSUE THREAD

**Issue by vincentlepot** [Tisseo/BoaBundle#1]
The bundle requires some configuration to run (under tisseo_boa). But no documentation is available.

I succeeded booting the kernel with the following block:

``` yaml
tisseo_boa:
  datatable_views:
    calendar_mixte: []
    default_view: []
    city_edit: []
```

Is it enough? What are the available options?
